FROM alpine:3.7

LABEL maintainer "https://github.com/onsoim"

# install python2
RUN apk add --no-cache python && \
    python -m ensurepip && \
    rm -r /usr/lib/python*/ensurepip && \
    pip install --upgrade pip setuptools && \
    rm -r /root/.cache